### PR TITLE
community/arrayfire: add -m32

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
I'm not familar with arrayfire/CUDA, but since the i686 package is build without CUDA, I wonder if `cuda` and `nvidia-utils` should be removed from optdepends?

**Comment by deep-42-thought** [comment]
I'm not familiar with that, either, but the versions for i686 and x86_64 are quite different currently, so I'd compare the same (old) versions to get an impression what the difference should be.

**Comment by ghost** [comment]
Yes, i686 was not updated to 3.5.0. I used the PKGBUILD from trunk. The old version was also built without `cuda` and `nvidia-tuils` but has the optdepends.

**Comment by deep-42-thought** [comment]
The oldest revision, still built for i686 was 7353fa73c9fb^ - which checks out to be identical for i686 and x86_64. So I would just assume, the minimal possible patch letting compilation succeed for i686 is what we want. I'm currently test-compiling yours - if it works, I'd use that and bother with dependencies if something looks wrong with the package afterwards ;-)

**Pull request merged**
