### PR TITLE
community/cringo: fixed building with g++ instead of clang++

### PR DESCRIPTION
**Pull request by andreasbaumann**

### CODE REVIEW

**Comment by andreasbaumann** [comment]
Maybe we wait for more answers on https://github.com/potassco/clingo/issues/57?

**Comment by deep-42-thought** [comment]
Your patch works, but we can wait for upstream - this build only blocks one other package.

**Comment by ghost** [comment]
I've just tested the upstream patch and it works. So until the next release this should work.
```bash
arch+=('i686')
source+=("clang-libatomic.patch::https://github.com/potassco/clasp/commit/fe3e176e2813956000bb947479de2c3d80fe34be.patch")
sha256sums+=('222b535ffd761c07c3652a3025180bcfb1f1b7504d7353048d5ce485a84c1a27')

prepare() {
  cd $pkgname-$pkgver/clasp
  patch -p1 -i ../../clang-libatomic.patch
}
```
P.S. I'm not sure about adding i686 to the arch array. Is it needed or will the build scripts handle that automatically?

Edit: Just prepending `-latimoc` to `LDFLAGS` works too.
```bash
export LDFLAGS="-latomic $LDFLAGS"
```

**Comment by andreasbaumann** [comment]
The i686 is added by the build scripts when knitting together the PKGBUILD from upstream and
the diff in the Archlinux32 packages repo.
Upstream I heard, that it's not really a requirement to use clang. And if the system C/C++ compiler
is gcc, we should maybe use this one. But this should then first be changed in the upstream 64-bit
PKGBUILD. We should thrive to be as minimal as possible when formulating the diff for 32-bit, so
actually I downvote my own pull request and I upvote your patch with -latomic.

**Pull request merged**
